compressionLevel: mixed

enableGlobalCache: false

enableTransparentWorkspaces: false

packageExtensions:
  rollup-plugin-pegjs@*:
    peerDependencies:
      pegjs: "*"

yarnPath: .yarn/releases/yarn-4.4.1.cjs
